README.md, states/CA/lower.yaml, states/CA/upper.yaml, states/UT/lower.yaml, states/UT/upper.yaml
And s/META_OFFICIAL_DISTRICT/META_OFFICIAL_DISTRICT_ZFILL on existing CA
configs.
With this, 6 out of 10 state legislatures are done, and the last 4 are the easiest ones!
Fixes https://github.com/resistbot/contact-officials/issues/9
=> UT state legislature

states/MD/lower.yaml, states/MD/upper.yaml
Thank heavens, finally a trivial one.
Fixes https://github.com/resistbot/contact-officials/issues/7
=> MD state legislature contact form config

README.md, states/SC/lower.yaml, states/SC/upper.yaml
And updates README with the latest in schema and meta variable tweaks.
Fixes https://github.com/resistbot/contact-officials/issues/8
=> SC legislature config

states/AZ/lower.yaml, states/AZ/upper.yaml, states/FL/upper.yaml
Fixes https://github.com/resistbot/contact-officials/issues/6
=> AZ legislature config

README.md, states/WA/lower.yaml, states/WA/upper.yaml
Fixes https://github.com/resistbot/contact-officials/issues/5
=> WA state legislature

states/TX/governor.yaml
Tested and working. Only pitfall is that we automatically check the box for a "Street Address" even if we do have a PO Box, since there's no way for us to tell the difference when processing the form.
=> Add TX gov config

states/FL/governor.yaml, states/MD/governor.yaml, states/OH/governor.yaml
These are all tested and working. https://github.com/j-ro/contact-states provided some helpful guidence, especially with the Ohio form which was a little tricky in selecting an issue/topic.
=> Add governor forms for FL, MD, and OH

states/AZ/governor.yaml
Tested working locally. Fixes #36.
=> Add form for Arizona governor

README.md, states/NJ/governor.yaml
Fixes #33. Adds new variable used into the README.
=> Add form for New Jersey governor

CODEOWNERS, README.md, states/FL/governor.yaml, states/MD/governor.yaml
Also updates URLs in FL and MD gov.
And adds Jason C and Chris E to code owners.
=> Update README to point to step-by-step gov guide.

states/NY/governor.yaml
=> Add NY Governor webform

README.md, states/SC/governor.yaml, states/WA/governor.yaml
@csnardi wrote SC gov, and turns out WA is similar. Both need to check for their success in an alert. Adds documentation of new `alert`  success checking that was added in https://github.com/resistbot/mercury/pull/103
Fixes https://github.com/resistbot/contact-officials/issues/35
Fixes https://github.com/resistbot/contact-officials/issues/37
=> SC and WA govs

states/NC/governor.yaml
=> Add NC Gov

states/MD/governor.yaml
When the Maryland governor's form switched to a new URL, the page itself also changed. Update the form config for the new page.
=> Update Maryland governor form config

CODEOWNERS, README.md, states/OK/governor.yaml, states/OK/lower.yaml, states/OK/upper.yaml
Fixes https://github.com/resistbot/contact-officials/issues/63
Fixes https://github.com/resistbot/contact-officials/issues/67
=> OK trifecta

states/DC/governor.yaml, states/NC/governor.yaml
Fixes #38 
Fixes #53 
NOTE: Mercury PR 106 is required for form-debugger to work with DC. https://github.com/resistbot/mercury/pull/106
=> Add dc mayor

states/VA/governor.yaml
Fixes #57 
Add VA Governor.
Note the form fields are within an iframe.  I just put the iframe source as the visit url.  If we have a better way of dealing with the iframe, let me know.
=> Add VA Governor

states/AK/governor.yaml
=> Add AK Governor

states/AL/governor.yaml
=> Add AL governor

states/CO/governor.yaml
=> Add CO Governor

states/ME/governor.yaml
=> Add ME Governor

states/NV/governor.yaml
=> Add NV Gov

states/OR/governor.yaml
=> Add or gov

states/MT/governor.yaml
=> Add MT Gov

states/WV/governor.yaml
=> Add WV governor.

states/FL/governor.yaml
The form for contacting Florida's governor changed, so update the form config for these changes. It now has a text captcha.
=> Update form config for Florida governor

states/CT/governor.yaml
Adds a form spec for the CT governor.
=> Add CT governor

states/IA/governor.yaml
=> Add IA governor

states/MN/governor.yaml
Tested and working. Fixes #96.
=> Add form config for Minnesota governor

states/LA/governor.yaml, states/WI/governor.yaml
Fixes #95 and requires mercury PR 111 to work.
Note this also contains an update for the WI governor form to play nice with the newer recaptcha selections required for LA.  
I tested AK (a kind of normal recaptcha), WI, LA and KY (To make sure I didn't break anything).
=> Add LA Governor 

states/KS/governor.yaml
Fixes #86 
Pretty straight forward.
=> Add KS Governor

states/NE/governor.yaml
=> Add NE Governor

states/NM/governor.yaml
=> Add NM Governor

states/SD/governor.yaml
=> Add SD Governor

states/MS/governor.yaml
Fixes #109 
Note this one give me a failure about 50% of the time with the page returning "Sorry an error occurred."
=> Add MS Governor

states/MO/governor.yaml
=> Add MO Governor

states/IL/governor.yaml
Work in Progress for #56 -- DO NOT MERGE
=> IL Governor

states/KS/governor.yaml
=> Add Address to KS Governor form

states/GA/governor.yaml
Fixes #134 
Note that this form is for the Governor's office of constituent services.  This is the only thing that's available for Georgia, and has only become available recently.
=> Add GA Governor

states/FL/lower.yaml
The form nearly completely changed, so update the form config to match.
=> Upload Florida lower house form config

README.md, states/KY/governor.yaml
For https://github.com/resistbot/mercury/pull/115. Also update the documentation to be correct.
=> Update selector to callback_selector for callback parameter

states/WI/governor.yaml
FIxes #156 
Note this is a two-step form now, but when my tests were failing on the second step, I still got an email confirmation.  ¯\_(ツ)_/¯
=> Update WI gov form

states/GA/governor.yaml
Updates the GA Governor form.  
NOTE:  A new directive has been added to Mercury to handle the pop-up alert.  This PR is required before this can be merged: https://github.com/resistbot/mercury/pull/118/files
=> Update GA Gov

states/OK/governor.yaml
Noticed a few errors on sends for OK Gov.  Form has been totally changed, so here are the updates.
=> Total rewrite of OK Governor

states/NV/governor.yaml
The form has been changed significantly here.  This PR fixes it up.
Fixes #163
=> 2019-05-06 - New NV Gov form

README.md, states/MI/governor.yaml
Fixes #176 
Adds recaptcha to MI Gov form.
=> 2019 05 21 mi gov recaptcha

states/AZ/governor.yaml
Fixes #178 
Phone number is now required, and there is a popup that needs to be closed.
=> Add phone and handling for pop up

states/AZ/governor.yaml
They took the pop up down, so we need to adjust.
=> Update AZ Gov to remove popup handling

states/PA/governor.yaml
Fixes #181 
PA Governor was updated under the hood.  Captcha removed.  Topic dropdown now mandatory.
=> 2019-06-13 - PA Gov general updates

states/MN/governor.yaml
The "would you like a reply" question has been removed from the form and this PR corrects that.
=> 2019-06-27 - Remove contact question from form

states/CT/governor.yaml
CT changed the location and configuration of their form.  This PR incorporates the latest version.
=> 2019-06-28 - Total rewrite of CT Governor form.

states/NV/governor.yaml
Total rewrite for NV Gov.
Note Mercury PR 125 (https://github.com/resistbot/mercury/pull/125) required for this form.
=> 2019-07-02 update nv gov

states/AZ/governor.yaml
AZ Governor forms changed.  I also reordered the yaml to match the form instead of grouping by action.  Personal preference that makes editing easier.
=> 2019-07-18 - Updates for AZ gov

states/NJ/governor.yaml
Mostly to change the url.  Other minor changes.
=> 2019-07-18 - Update NJ Gov link and misc

states/ND/governor.yaml
ND Gov form changed.  
Note the 7 second wait.  The form didn't like how fast we are filling it out, and returns a message that says "please wait six seconds," so I choose seven.  Feedback welcome.  :)
=> 2019-07-23-Update ND Gov

states/AZ/governor.yaml
AZ Gov changed the CSS selectors under the page, so this update fixes all that.
=> 2019-08-01 - Update AZ again

states/WA/governor.yaml
WA has an additional click on a confirmation screen.
=> 2019-08-13 - Handle WA Gov confirm screen

states/ME/governor.yaml
ME Governor changed.  This updates our files accordingly.
=> 2019-08-14 - Update ME Gov form

states/GA/governor.yaml
=> 2019-08-15 - Updates for GA Gov form

states/AZ/lower.yaml, states/AZ/upper.yaml
AZ State Legislature updated their captcha.
Because Robots.
=> 2019-08-30 - Updates for AZ state legislature captcha.

states/WI/governor.yaml
WI Gov form changed.... again.  This gets it back to good.
=> 2019-09-22 - Updates for the WI governor form

states/MD/governor.yaml
Recaptcha has been removed.
Success message changed.
=> 2019-10-08 Update MD Gov

states/NH/governor.yaml
few things changed, causing forms to fail.
=> 2019-10-14 - Update NH Gov

states/VT/governor.yaml
=> 2019-11-04 - Add Recaptcha to VT Gov form

states/GA/governor.yaml
=> 2019-12-07 - Remove recaptcha

states/KY/governor.yaml
=> 2020-01-21 - Update KY Gov url

states/FL/lower.yaml
Changed the address 2 field, which broke our form.
=> 2020-01-21 - Tweak for FL lower.

states/CO/governor.yaml
Updates for CO gov. 
Note there is a topic and subtopic pair.  The subtopic items are always present in the html, but selecting one that isn't related to the parent topic causes the form to fail.  Because of this, random selection does not work.  Hard coded the topic and subtopic to something generic for now.
=> 2020-03-18 - Updates for CO governor

states/AZ/governor.yaml
=> 2020-03-26 - Update AZ Gov success message

states/KY/governor.yaml
=> 2020-03-26 - Update KY gov

states/KY/lower.yaml, states/KY/upper.yaml
Changed from a fill in to a drop down.
=> 2020-06-05 - Update state to select element

states/MN/governor.yaml
Added a little wait time for the captcha to resolve.
=> 2020-07-21 - Add some wait time for the captcha to come back.

states/GA/governor.yaml
=> 2020-08-10 - Update GA Gov form

states/GA/governor.yaml
Helping us deal with the character limitation on the form
=> 2020-08-15 - GA Gov replace newline with a single space in message

states/MT/governor.yaml
This adds MT gov for the new term.
Note this was a form we struggled with in the past, and it's now working.
=> 2021-01-14 - MT gov for 2021

whitehouse/president.yaml
hey that rhymes.
46's form needs a fix for the submit button.
=> 2021-02-15 - fix forty-six

states/NY/governor.yaml
Let's make sure we get Cuomo his final correspondence.
=> 2021-08-11 - update NY gov

states/TN/governor.yaml
=> 2021-08-16 - Update TN Gov

states/IN/governor.yaml
=> 2022-02-07 update IN governor

states/CA/lower.yaml
Fixes a newline that was missing.
@chris-erickson I think this has been borked for a while, but the volume was low so it flew under the radar.
=> 2022-02-07- fix CA lower

states/OH/lower.yaml
=> 2022-02-07 - update OH lower

whitehouse/president.yaml
=> 2022-04-28 - Update prez

CODEOWNERS
=> 2022-06-14 - update codeowners

states/AR/governor.yaml, states/AZ/governor.yaml, states/MA/governor.yaml
=> 2023-01-16 updates

states/CA/governor.yaml
New form is entirely React so it got a bit harder to update.
=> Fix CA governors new react form

states/IN/governor.yaml
Button was so close to the edge of the page, I think it was possibly obscured.
=> Update IN Governor

whitehouse/README.md
This should resolve the import error.
=> Add WH note
