states/CA/lower.yaml
states/CA/upper.yaml

It seems as if "you for contacting" isn't broad enough for all forms, so try using "hank you" since every form seems to have "thank you" or "Thank you".

Attempt different success text for CA legislature

---

README.md
states/TX/lower.yaml
states/UT/upper.yaml

TX lower: last week it added a subject selector, this week it changed
back to a text input for subject! WTF?!?!
UT upper: senator contact form moved from a centralized URL to being a
form on each senator's webpage.

Fix TX and UT state leg forms

---

README.md
states/CA/lower.yaml
states/CA/upper.yaml

With the new selector attribute for the success section, we should now detect success properly for all CA legislators. Switch to using this attribute, and add information to the README about it.

Use new selector attribute for CA legislature success

---

states/FL/governor.yaml

The captcha image apparently takes a little bit to load, and trying to screenshot it beforehand results in an error since it's a broken image. Add a wait of 5 seconds to prevent this problem.

Add a wait to Florida governor form config

---

states/OH/lower.yaml
states/OH/upper.yaml

We currently visit the URL of the legislator and then click their contact button which takes you to their URL plus `/contact`. Instead, we can instead go directly there from the beginning.

Use more direct URL for Ohio legislature form config

---

states/IA/governor.yaml

It seems that the IA governor form uses a spam-detection technique of checking how long was spent between visiting the form and actual form submission. 5 seconds plus the additional time needed to fill out the form should be enough to not be detected as spam, so add a 5 second wait.

Add a wait to IA governor form config

---

states/GA/governor.yaml

Seems as if the selector changed, so switch to using the id. This also is not a required field, so switch to selecting "- None -" as that'll be most likely more accurate.

Update related agency selection for GA governor

---

states/GA/governor.yaml

This is now a select and not a list of radio buttons, so fix that as well.

Use select in agency selection for GA governor

---

states/NY/governor.yaml

Fixes #149 
I tested this by forcing "Dr." as a the value for the prefix.  Predictably, an error is produced in the logs, but form_processor continues.  Then the new JS changes the value to blank before hitting the submit button, and the form is successful.
I also tested "Mr." and the JS does not change it to blank, which is expected behavior.

Update NY Gov form for a prefix not available on the form select

---

states/CO/governor.yaml

A recaptcha was added, which we need to account for. Additionally switch to using the original URL instead of the iframe as the iframe URL on the page seemed to change already within a month.

Update Colorado governor form config

---

states/CO/governor.yaml

I forgot why we used the iframe URL: Selenium has a hard time with iframes and thus doesn't see elements inside of the iframe. Switch to an (updated) version of the iframe URL to avoid this.

Switch back to iframe URL for Colorado governor

---

states/NJ/governor.yaml

The success text for the New Jersey governor's contact form seems to have changed. Update to reflect the new text.

Update success text for New Jersey governor

---

states/WI/governor.yaml

The click_on directive doesn't work on this checkbox, but object.click() does.  
Fixes #168

2019-05-09 - Add confirmation checkbox.

---

states/CA/governor.yaml

CA Governor form had a "do you want a reply?" question on the first page.  Seems they are no longer interested, as that question is no longer present.  Form changes to reflect that.

2019-07-01 - Remove reply question

---

states/LA/governor.yaml

Either they changed the page, or it behaves differently because of our recent changes to recaptcha handling.  I'm kinda ruling out the latter because the element we previously looking for isn't present.  
Either way, removing the specific selector fixes it.

2019-07-24 - Remove unnecessary recaptcha selector

---

states/NJ/governor.yaml

This is a quick update to use just the 5 digit zip instead of the zip and +4.  
The NJ gov from wants either 5 digits, or NNNNN-NNNN when the +4 is included.  We are concatenating all nine digits together, without a hyphen, and that causes a failure.  The 5 digit zip is sufficient. 
Additionally, it appears that we might expect to be using the NNNNN-NNNN format (with hyphen), but in reality we are not.  There are a few forms out there that use it, and since they are working at this point, I'm hesitant to change it.  If it ain't broke, don't fix it.

2019-08-05 - Use zip5 for NJ Gov

---

states/FL/lower.yaml

FL appears to have updated the success criteria.  This PR addresses that.  
(I did check FL upper as well, and they have not changed.)

2019-10-14 - Update FL Lower success criteria.

---

states/NV/governor.yaml

The browser alert we are searching for to find the success criteria is showing the ascii code for the space between the two words.  I don't know why.  Trimmed down to just get a single word. 
"Thank%20You"

2020-03-18 - Update NV Gov success criteria

---

states/MN/governor.yaml

MN Governor is redirecting to a recaptcha before even loading the form (which also has a recaptcha on it :eyeroll:).  A regular browser doesn't seem to catch the redirect, but we seem to be getting it consistently in Mercury.  We can watch it and see if we have any strange failures.

2020-06-15 - Update MN Gov for additional recaptcha

---

states/AK/governor.yaml
states/AL/governor.yaml
states/CT/governor.yaml
states/DC/governor.yaml
states/IN/governor.yaml
states/MI/governor.yaml
states/NC/governor.yaml
states/NY/governor.yaml
states/PA/governor.yaml
states/RI/governor.yaml
states/TN/governor.yaml

Uncomment any existing max_length since we can now utilize them in Mercury.  Also update to the newest key format to match openstates.  
I also reviewed each form that had an existing max_length specified to make sure they were still valid.

2020-08-10 - Implement max length

---

states/MN/city/Minneapolis/mayor.yaml

This adds the Minneapolis Mayor form.
Note, the state drop down is some weird thing that isn't really a select.  Since we wouldn't route anyone outside of MN to this form, I just hardcoded MN in the config.
We'll figure out how to add the webform delivery method in discovery next.

2020-11-20 - Add Minneapolis Mayor form

---

states/IL/governor.yaml

So they reused the element, but changed it to link to the Governor's Twitter page.  It doesn't prevent the form from proceeding, so I just removed it.

2021-08-11 - Update IL Gov form

---

congress/P000603.yaml

TBD if we actually need this anymore, it's a clone of contact-congress. It might be to assist with Discovery integration tests, but could be removed if that appears to remain operational.

Update Ron Paul
